services:
  app:
    build: .
    container_name: app
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    stdin_open: true
    tty: true
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: noir
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432